version: "3"

services:
  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - keycloak
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=fastapi
      - SECRET_KEY=private_key
      - KEYCLOAK_SERVER_URL=http://keycloak:8080/auth/
      - KEYCLOAK_CLIENT_ID=myapp
      - KEYCLOAK_REALM_NAME=yassaminakh
      - KEYCLOAK_CLIENT_SECRET_KEY=
      
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=fastapi
    volumes:
      - db-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
      
  keycloak:
    image: jboss/keycloak:13.0.0
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"

volumes:
  db-data:
