FROM jboss/wildfly:14.0.1.Final

COPY realm.json /opt/jboss/wildfly/standalone/configuration/
COPY modules/ /opt/jboss/wildfly/modules/
COPY deployments/ /opt/jboss/wildfly/standalone/deployments/

RUN /opt/jboss/wildfly/bin/add-user.sh admin admin --silent

CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0"]