"""auto-doctors

Revision ID: 1362b72e1d25
Revises: 7bdc2d841021
Create Date: 2023-02-16 20:43:35.774695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1362b72e1d25'
down_revision = '7bdc2d841021'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
