"""auto-patients

Revision ID: 7bdc2d841021
Revises: fd19cc55dde6
Create Date: 2023-02-16 20:42:51.628901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bdc2d841021'
down_revision = 'fd19cc55dde6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
