"""auto-appointments

Revision ID: c455e6028e27
Revises: 40ad0cb0c656
Create Date: 2023-02-16 20:39:15.601961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c455e6028e27'
down_revision = '40ad0cb0c656'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
