"""auto-doctors

Revision ID: fd19cc55dde6
Revises: c455e6028e27
Create Date: 2023-02-16 20:39:59.154390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd19cc55dde6'
down_revision = 'c455e6028e27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
